### ISSUE TITLE
移除shiro安全框架后模板没有同步更新

### ISSUE THREAD

**Issue by fortoken** [yzcheng90/X-SpringBoot#10]
v3.0

项目部分重构，精简部分代码
springboot 版本升级到 2.1.8
移除shiro 安全框架
新增spring security 安全框架

---------------------------------------------------------------------------
生成Controller代码的模板没有同步更新，仍然引入了shiro相关，导致新生成的代码编译不过

**Comment by yzcheng90** [comment]
好的，有时间我更新一下

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：fortoken <notifications@github.com>
发送时间：2020-02-28 08:06
主题：Re: [yzcheng90/X-SpringBoot] 移除shiro安全框架后模板没有同步更新 (#10)
收件人："yzcheng90/X-SpringBoot"<X-SpringBoot@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Closed #10.
