### ISSUE TITLE
[Request]如何在本框架内配置多数据源（一个Mysql一个Oracle）

### ISSUE THREAD

**Issue by hank-hong** [yzcheng90/X-SpringBoot#11]
您好，

我使用的X-SpringBoot版本为2.1.2，请问本框架是否支持多数据源配置？

如果可以请问如何配置？

**Comment by yzcheng90** [comment]
可以试试mybatis plus 动态数据源 https://mp.baomidou.com/guide/dynamic-datasource.html

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：czx <notifications@github.com>
发送时间：2020-03-07 08:31
主题：Re: [yzcheng90/X-SpringBoot] [Request]如何在本框架内配置多数据源（一个Mysql一个Oracle） (#11)
收件人："yzcheng90/X-SpringBoot"<X-SpringBoot@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Closed #11.

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：hank-hong <notifications@github.com>
发送时间：2020-03-02 14:09
主题：[yzcheng90/X-SpringBoot] [Request]如何在本框架内配置多数据源（一个Mysql一个Oracle） (#11)
收件人："yzcheng90/X-SpringBoot"<X-SpringBoot@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

您好，
我使用的X-SpringBoot版本为2.1.2，请问本框架是否支持多数据源配置？
如果可以请问如何配置？
