### ISSUE TITLE
访问localhost返回了字符串{"msg":"hello welcome to use x-springboot","code":0}

### ISSUE THREAD

**Issue by Lambert6** [yzcheng90/X-SpringBoot#12]

**Comment by Lambert6** [comment]
已解决，nginx配置文件有误，win10操作系统需要在静态资源文件路径上加双斜杠\\   例如：C:\\tem\\X-SpringBoot-master\\x-springboot-ui

**Comment by Lambert6** [comment]
双右斜杠

**Comment by yzcheng90** [comment]
这个问题是 目录带T开头的话 会自动被转义。。。变成\t  空格了
解决方法是可以改成正斜杠或双反斜杠

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：czx <notifications@github.com>
发送时间：2020-04-21 17:17
主题：Re: [yzcheng90/X-SpringBoot] 访问localhost返回了字符串{"msg":"hello welcome to use x-springboot","code":0} (#12)
收件人："yzcheng90/X-SpringBoot"<X-SpringBoot@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Closed #12.

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：Lambert6 <notifications@github.com>
发送时间：2020-03-18 10:12
主题：Re: [yzcheng90/X-SpringBoot] 访问localhost返回了字符串{"msg":"hello welcome to use x-springboot","code":0} (#12)
收件人："yzcheng90/X-SpringBoot"<X-SpringBoot@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

双右斜杠

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：Lambert6 <notifications@github.com>
发送时间：2020-03-17 18:06
主题：[yzcheng90/X-SpringBoot] 访问localhost返回了字符串{"msg":"hello welcome to use x-springboot","code":0} (#12)
收件人："yzcheng90/X-SpringBoot"<X-SpringBoot@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>
