### ISSUE TITLE
request.getParameter("captcha");  doFilterInternal

### ISSUE THREAD

**Issue by lovehua** [yzcheng90/X-SpringBoot#14]
rotected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) {

        String url = request.getRequestURI();
        if (pathMatcher.match(Constant.TOKEN_ENTRY_POINT_URL,url)){
            String captcha = request.getParameter("captcha");
            String randomStr = request.getParameter("randomStr");
            String username=request.getParameter("username");

         }
}

大神 无法获取到值是怎么 回事，新手请多指教

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：lovehua <notifications@github.com>
发送时间：2020-04-16 17:00
主题：Re: [yzcheng90/X-SpringBoot] request.getParameter("captcha"); doFilterInternal (#14)
收件人："yzcheng90/X-SpringBoot"<X-SpringBoot@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Closed #14.
