### ISSUE TITLE
AbstractController#getUser类型转换异常问题

### ISSUE THREAD

**Issue by KitGavinx** [yzcheng90/X-SpringBoot#15]
强转有问题...原因有待研究
		if(object != null){
			return (CustomUserDetailsUser) object;
		}
		return object;

此处类型转换异常是由于spring-boot-devtools造成的，

去掉一下依赖即可解决
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <optional>true</optional>
        </dependency>

参考来源：https://blog.csdn.net/yuqiling0818/article/details/101064389

**Comment by zlf2002171** [comment]
unsubscribe


2020-05-18 

zlf2002171 



发件人：zhu <notifications@github.com>
发送时间：2020-04-30 12:39
主题：[yzcheng90/X-SpringBoot] AbstractController#getUser类型转换异常问题 (#15)
收件人："yzcheng90/X-SpringBoot"<X-SpringBoot@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

	强转有问题...原因有待研究
	if(object != null){
		return (CustomUserDetailsUser) object;
	}
	return object;

此处类型转换异常是由于spring-boot-devtools造成的，
去掉一下依赖即可解决

org.springframework.boot
spring-boot-devtools
true

参考来源：https://blog.csdn.net/yuqiling0818/article/details/101064389

**Comment by yzcheng90** [comment]
感谢，已修复
