### ISSUE TITLE
无法引入依赖

### ISSUE THREAD

**Issue by G233** [yzcheng90/X-SpringBoot#16]
![image](https://user-images.githubusercontent.com/39009225/84597042-ba76e100-ae93-11ea-8582-60b51e0c6913.png)

**Comment by yzcheng90** [comment]
配置本地maven 然后用阿里的镜像

`
<mirrors>
   <mirror>
    <id>alimaven</id>
    <name>aliyun maven</name>
    <url>http://maven.aliyun.com/nexus/content/groups/public/</url>
    <mirrorOf>central</mirrorOf>
</mirror>
  <mirror>
    <id>osc</id>
    <mirrorOf>*</mirrorOf>
    <url>http://maven.oschina.net/content/groups/public/</url>
    </mirror>
</mirrors> 
`
