### ISSUE TITLE
前段Module目录下HTML修改无法生效，始终有缓存，重启NGINX也没作用

### ISSUE THREAD

**Issue by hank-hong** [yzcheng90/X-SpringBoot#17]
前段页面例如.../sys/user.htmlL，在其中简单修改了一些描述后重启NGINX也不起作用。

在VUE中跳转页面的修改都不起作用，即使所有页面都添加了清除缓存标识也不起作用，如下：
```
<meta http-equiv="Expires" content="0">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Cache-control" content="no-cache">
<meta http-equiv="Cache" content="no-cache">
```

在INDEX.HTML中修改时起效的，但是只要在MODULES下的页面不管如何重启，请缓存都不起作用。

请问这种情况是什么原因造成的？

**Comment by yzcheng90** [comment]
用无痕模式

**Comment by ZhujingJava** [comment]
。


---原始邮件---
发件人: &quot;czx&quot;<notifications@github.com&gt;
发送时间: 2020年9月11日(周五) 下午5:56
收件人: &quot;yzcheng90/X-SpringBoot&quot;<X-SpringBoot@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: Re: [yzcheng90/X-SpringBoot] 前段Module目录下HTML修改无法生效，始终有缓存，重启NGINX也没作用 (#17)




 
Closed #17.
 
&mdash;
