### ISSUE TITLE
报禁止跨域错误

### ISSUE THREAD

**Issue by ddddage** [yzcheng90/X-SpringBoot#19]
![image](https://user-images.githubusercontent.com/25663972/88026139-ff172b80-cb67-11ea-9e74-8bf4fb0d835c.png)
![image](https://user-images.githubusercontent.com/25663972/88026159-09d1c080-cb68-11ea-80d1-28d31a62bb21.png)
![image](https://user-images.githubusercontent.com/25663972/88026169-0dfdde00-cb68-11ea-9bb0-6ebceac2d2bf.png)
![image](https://user-images.githubusercontent.com/25663972/88026225-2110ae00-cb68-11ea-8022-c0f4f317eab4.png)
项目能正常启动,没有改代码,但是报跨域错误,用的项目自带的nginx配置,求解答

**Comment by yzcheng90** [comment]
在common.js 中的baseUrl 如果配置是localhost  那就访问localhost，如果配置的是IP，那就用IP访问，如果还不行，那就加下面的QQ群吧
