### ISSUE TITLE
html,js缓存好厉害

### ISSUE THREAD

**Issue by liuxingtianxia** [yzcheng90/X-SpringBoot#2]
html,js缓存，刷新页面依然存在，楼主怎么解决的？

**Comment by yzcheng90** [comment]
#建议用热部署插件(***提升效率必装***)
IDEA 插件 ：Jrebel
安装参考：
https://jingyan.baidu.com/album/ac6a9a5e31417c2b653eace8.html?picindex=1
不然修改了html js  要重启服务
