### ISSUE TITLE
部署在云服务器，登录管理后台出现跨域

### ISSUE THREAD

**Issue by HuanYuanHe** [yzcheng90/X-SpringBoot#22]
![image](https://user-images.githubusercontent.com/51042672/102588349-4706a280-4148-11eb-8ee4-bada5d320f57.png)
请问下这个跨域问题该怎么解决呢  接受图片验证码的接口倒是可以正常访问

**Comment by HuanYuanHe** [comment]
解决了  云服务器nginx问题

**Comment by FengJianche** [comment]
1
