### ISSUE TITLE
一个小疑惑

### ISSUE THREAD

**Issue by Gabriel-1023** [yzcheng90/X-SpringBoot#30]
可能是我Spring还没有学明白，不太理解为什么com/suke/czx/authentication/SecurityConfigurer.java 中的authenticationSuccessHandler() 等方法要手动 new 实例，而不是使用依赖注入的方式呢？谢谢！

**Comment by yzcheng90** [comment]
这个 AuthenticationSuccessHandler 接口 springsecurity 没有使用bean查找注入，而是new了一个默认实现，所以如果要自定义只能再给一个自定义实现去set 替换
