### ISSUE TITLE
swagger-ui上面的接口测试会发生跨域问题

### ISSUE THREAD

**Issue by xuanyuan1hao** [yzcheng90/X-SpringBoot#5]
swagger-ui上面的接口测试会发生跨域问题，测试不通过。看看咋处理

**Comment by xuanyuan1hao** [comment]
nginx启动的是80端口，项目启动的是8080端口，swagger访问的服务是8080端口，所以会跨域，我看了在springboot的filter已经处理了跨域，但是浏览器chrome一样报错。返回内容为空。

**Comment by yzcheng90** [comment]
项目中有一个hello接口 测试 是没有问题的，还有就是 你可以在Swagger2 配置类中指定请求的host 为ip 或域名

**Comment by xuanyuan1hao** [comment]
谢谢！，已经搞定。




 
---原始邮件---
发件人: "czx"<notifications@github.com>
发送时间: 2019年5月27日(星期一) 晚上8:24
收件人: "yzcheng90/X-SpringBoot"<X-SpringBoot@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"xuanyuan1hao"<383063671@qq.com>;
主题: Re: [yzcheng90/X-SpringBoot] swagger-ui上面的接口测试会发生跨域问题 (#5)



项目中有一个hello接口 测试 是没有问题的，还有就是 你可以在Swagger2 配置类中指定请求的host 为ip 或域名

**Comment by qixianchuan** [comment]
我也遇到了这个问题，请问您是怎么解决的？

**Comment by figozhu** [comment]
> 谢谢！，已经搞定。
> […](#)
> ---原始邮件--- 发件人: "czx"<notifications@github.com> 发送时间: 2019年5月27日(星期一) 晚上8:24 收件人: "yzcheng90/X-SpringBoot"<X-SpringBoot@noreply.github.com>; 抄送: "Author"<author@noreply.github.com>;"xuanyuan1hao"<383063671@qq.com>; 主题: Re: [yzcheng90/X-SpringBoot] swagger-ui上面的接口测试会发生跨域问题 (#5) 项目中有一个hello接口 测试 是没有问题的，还有就是 你可以在Swagger2 配置类中指定请求的host 为ip 或域名 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

这种恶习真是讨厌，一句话“已经搞定”，怎么搞定的就是不说，不能让后来人分享你成功的经验吗？
