### ISSUE TITLE
关于框架中的一些小问题反馈

### ISSUE THREAD

**Issue by justforhing** [yzcheng90/X-SpringBoot#6]
首先非常感谢作者原创的此框架， 让我开发更加高效，在使用中发现了框架中的一部分小问题，在此想提出来和作者交流一下， 可能有些并非bug，而是框架设计本身就是这样的，具体发现的问题如下：

1.退出登录时权限没有废除，后续无论什么角色登录都是同样的权限，这里检查了一下，可能是在SysUserTokenServiceImpl的logout()方法中退出登录只是删除了数据库中的token(同时这里有个小疑问，token存数据库的目的是什么？)，而没有使用SecurityUtils.getSubject().logout();废除用户权限
2.角色菜单更新失效，这里检查了一下应该是缺少了SysRoleController的修改角色方法中缺少了sysRoleMenuService.saveOrUpdate(role.getRoleId(),role.getMenuIdList());更新权限的语句
3.生成模板中大小写mapper（应当大写，但是这里模板中是小写）问题：这个之前有在框架讨论群中咨询过，生成模板需要统一才能自定义Mapper内容，否则映射不上，还要抛异常
4.SysRoleMenuServiceImpl中保存角色菜单时，原本是直接根据角色和菜单所关联的这个ID删除，其实逻辑上应按照roleId删除，我理解这个保存函数的步骤是先删除当前角色的所有权限，再将新权限赋给当前角色。

**Comment by yzcheng90** [comment]
感谢，最近加班，有时间我检查一下

**Comment by yzcheng90** [comment]
bug已经修复，及时更新
