### ISSUE TITLE
每次点按钮，都会调用两次api

### ISSUE THREAD

**Issue by loong-chen** [yzcheng90/X-SpringBoot#8]
发现两个问题：
1，每次点按钮，api调用两次
2，新建的表，通过自动生成的代码，接口访问报404，实际有那个接口

**Comment by yzcheng90** [comment]
麻烦给个重现步骤

**Comment by loong-chen** [comment]
登录后按 F12，打开浏览器调试工具，随便点一个菜单，可以看到执行了两次接口
![image](https://user-images.githubusercontent.com/28297245/62445259-63dc4900-b792-11e9-9fe2-22a5eaf17f92.png)

**Comment by caorongzhe** [comment]
options是预检请求，不用管， 另外一条是不是 GET或者POST等
